### ISSUE TITLE
adhere to c++11 standard

### ISSUE THREAD

**Issue by ravil-mobile** [NehilDanis/plane_segmentation#2]
Hi again, 

Could you, please, use `using` keyword instead of `typedef`. It is not a big issue but it would be nice

https://github.com/NehilDanis/plane_segmentation/blob/84882c3f9de6509c9936c642aa52b2dae91db0fa/segmentation.cpp#L9-L10

**Comment by NehilDanis** [comment]
Hey Ravil, thanks for the comment. I have changed the code accordingly!
